services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb+srv://uppalapatipranita:Aypravija%4009@cluster0.vr7zw.mongodb.net/activity-tracker?retryWrites=true&w=majority

  mongo:
    image: mongo
    ports:
      - "27017:27017"

